# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20160606_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='app01.UserProfile'),
        ),
    ]
