# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20160607_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('view_task', '查看所有的任务'), ('change_task_status', '修改所有任务'), ('close_task', '关闭所有任务'))},
        ),
    ]
