# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20160616_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('view_userprofile', '查看userprofile记录'), ('view_index', '查看主页'))},
        ),
    ]
