# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20160616_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyrecord',
            options={'permissions': (('view_studyrecord', '查看学习记录'), ('view_statics', '查看班级统计信息'), ('search_statics', '搜索班级统计信息'))},
        ),
    ]
